version: '3'

env:
  GOOS: "{{OS}}"

tasks:
  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run ./... -v --timeout 5m

  scan:
    desc: Run security scan
    cmds:
      - gosec -conf .gosec.config.json "./..."

  tools:
    desc: Install tools
    cmds:
      - task: tools:install:golangci-lint
      - task: tools:install:gosec

  tools:install:golangci-lint:
    desc: Install golangci-lint
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

  tools:install:gosec:
    desc: Install gosec
    cmds:
      - go install github.com/securego/gosec/v2/cmd/gosec@latest
