project_name: Hotpot
before:
  hooks:
    - go mod tidy
builds:
  - env: [CGO_ENABLED=0]
    binary: hotpot
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    id: "cli"
    dir: .
    main: ./cmd/cli/main.go
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.Commit={{.Commit}} -X main.Date={{.Date}}

archives:
  - id: cli-archive
    format: tar.gz
    files:
      - none*
    builds:
      - cli
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^conf:'
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
signs:
  - cmd: gpg
    args:
      - --output
      - $signature
      - --detach-sig
      - $artifact
    signature: ${artifact}.sig
    artifacts: none
release:
  github:
    owner: zcubbs
    name: hotpot
  draft: false
  prerelease: auto
  header: |
    ## ({{ .Date }})

    Welcome to this new release!
  footer: |
    ## Thanks!
    Those were the changes on {{ .Tag }}!
  name_template: "{{.Tag}}"
