version: '3'

vars:
  GOOS: "{{OS}}"

tasks:

  test:
    cmds:
      - go test ./...

  build:linux:
    cmds:
      - go env -w GOOS=linux GOARCH=amd64
      - go build -o bin/hotpot cmd/cli/main.go

  build:windows:
    cmds:
      - go env -w GOOS=windows GOARCH=amd64
      - go build -o bin/hotpot.exe cmd/cli/main.go

  lint:
    cmds:
      - golangci-lint run ./... -v --timeout 5m

  scan:
    cmds:
      - gosec -conf .gosec.config.json "./..."

  tools:install:golangci-lint:
    desc: Install golangci-lint
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

  tools:install:gosec:
    desc: Install gosec
    cmds:
      - go install github.com/securego/gosec/v2/cmd/gosec@latest
