---

node:
  check: true
  ip: 127.0.0.1
  minDiskSize:
    - path: /
      size: 80G
  minMemory: 8G
  minCpu: 4
  supportedOs:
    - linux
  supportedArch:
    - x86_64
    - amd64
  supportedDistros:
    - name: ubuntu
      version: 20.04
  curl:
    - https://github.com

k3s:
  enabled: true
  version: v1.21.2+k3s1
  kubeApiAddress: https://127.0.0.1:6443
  tlsSan:
    - 127.0.0.1
#  resolvConfPath: /etc/k3s-resolv.conf
  dataDir: /data/k3s
  defaultLocalStoragePath: /data/local-path-provisioner
  purgeExisting: false
  purgeExtraDirs:
    - /data/k3s
    - /data/local-path-provisioner

certManager:
  enabled: true
  purgeExisting: false
  letsencryptIssuerEnabled: true
  letsencryptIssuerEmail: test@example.com
  letsEncryptIngressClassResolver: traefik
  httpChallengeEnabled: false
  dnsChallengeEnabled: false
  dnsProvider: azure # ovh, azure, cloudflare or route53
#  dnsRecursiveNameservers:
#    - 168.63.129.16:53
#  dnsRecursiveNameserversOnly: true
  dnsAzureClientID: env.HOTPOT_DNS_AZURE_CLIENT_ID
  dnsAzureClientSecret: env.HOTPOT_DNS_AZURE_CLIENT_SECRET
  dnsAzureHostedZoneName: example.com
  dnsAzureResourceGroupName: env.HOTPOT_DNS_AZURE_RESOURCE_GROUP_NAME
  dnsAzureSubscriptionID: env.HOTPOT_DNS_AZURE_SUBSCRIPTION_ID
  dnsAzureTenantID: env.HOTPOT_DNS_AZURE_TENANT_ID

traefik:
  enabled: true
  purgeExisting: false
  enableAccessLog: true
  enableDashboard: true
  forwardHeaders: true
  forwardHeadersInsecure: true
  proxyProtocol: true
  proxyProtocolInsecure: true
  transportInsecure: true
  ingressProvider: traefik
  dnsChallenge: true
  dnsChallengeProvider: ovh
  dnsChallengeResolverEmail: test@example.com
#  dnsChallengeResolverIPs: "1.1.1.1:53,8.8.8.8:53"
#  defaultCertificateEnabled: true
#  defaultCertificateCert: env.HOTPOT_DEFAULT_CERTIFICATE_CERT
#  defaultCertificateKey: env.HOTPOT_DEFAULT_CERTIFICATE_KEY
  debug: true

secrets:
  enabled: true
  containerRegistries:
    - name: dockerhub
      url: HOTPOT_CONTAINER_REGISTRY_URL
      username: env.HOTPOT_CONTAINER_REGISTRY_USERNAME
      password: env.HOTPOT_CONTAINER_REGISTRY_PASSWORD
      namespaces:
        - hub

argocd:
  enabled: true
  purgeExisting: false
  adminPassword: env.HOTPOT_ARGOCD_ADMIN_PASSWORD
  adminPasswordHashed: false

gitops:
  enabled: true
  purgeExisting: false
  projects:
    - name: hotpot
      description: Hotpot GitOps
      repositories:
        - name: gitops-private-repo
          url: https://github.com/zcubbs/hotpot-gitops-test-private-repo
          type: git
          credentials:
            username: env.HOTPOT_GITOPS_REPO_USERNAME
            password: env.HOTPOT_GITOPS_REPO_PASSWORD
        - name: helm-private-repo
          url: https://github.com/zcubbs/hotpot-charts-test-private-repo
          type: helm
          isOci: true
          credentials:
            username: env.HOTPOT_HELM_REPO_USERNAME
            password: env.HOTPOT_HELM_REPO_PASSWORD
      apps:
        - name: hub
          repo: https://github.com/zcubbs/hotpot-gitops-test-private-repo
          path: hub/chart
          revision: main
          namespace: hub
          createNamespace: true
          isHelm: true
          isOci: false
          valuesFiles:
            - values.yaml
          prune: true
          selfHeal: true
