name: Hot Meal
debug: true

ingredients:
  node:
    ip: 127.0.0.1
    minDiskSize:
      - path: /
        size: 80G
    minMemory: 8G
    minCpu: 4
    supportedOs:
      - linux
    supportedArch:
      - x86_64
      - amd64
    supportedDistros:
      - name: ubuntu
        version: 20.04
    curl:
      - https://github.com
#    telnet: # removed as port scanning might be flagged by AV
#      - 127.0.0.1:80
#    ssh: # removed for now
#      - 127.0.0.1


  certManager:
    enabled: false

  k3s:
    enabled: true
    version: v1.21.2+k3s1
    tlsSan:
      - 127.0.0.1
    dataDir: /data/k3s
    defaultLocalStoragePath: /data/local-path-provisioner
    purgeExisting: false

  traefik:
    enabled: true
    purgeExisting: false
    enableAccessLog: true
    enableDashboard: true
    forwardHeaders: true
    forwardHeadersInsecure: true
    proxyProtocol: true
    proxyProtocolInsecure: true
    dnsChallenge: true
    dnsChallengeProvider: ovh
    dnsChallengeResolverEmail: test@example.com
    debug: true

  argocd:
    enabled: true
    purgeExisting: false
    credentials:
      username: admin
      password: ARGOCD_ADMIN_PASSWORD
      useEnv: true
    projects: []
